name: package-deploy

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches: 
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Check out Code 
      uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build solution and generate NuGet package
      run: |  
        cd MikyM.Utilities
        dotnet pack -c Release -o out 
    - name: Push generated package to NuGet registry
      run: dotnet nuget push ./MikyM.Utilities/out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json